// @ts-nocheck
import { browser } from 'fumadocs-mdx/runtime/browser';
import type * as Config from '../source.config';

const create = browser<typeof Config, import("fumadocs-mdx/runtime/types").InternalTypeConfig & {
  DocData: {
  }
}>();
const browserCollections = {
  docs: create.doc("docs", {"cloud.mdx": () => import("../content/docs/cloud.mdx?collection=docs"), "configuration.mdx": () => import("../content/docs/configuration.mdx?collection=docs"), "faq.mdx": () => import("../content/docs/faq.mdx?collection=docs"), "git-hooks.mdx": () => import("../content/docs/git-hooks.mdx?collection=docs"), "hooks.mdx": () => import("../content/docs/hooks.mdx?collection=docs"), "index.mdx": () => import("../content/docs/index.mdx?collection=docs"), "mcp.mdx": () => import("../content/docs/mcp.mdx?collection=docs"), "monorepos.mdx": () => import("../content/docs/monorepos.mdx?collection=docs"), "rules.mdx": () => import("../content/docs/rules.mdx?collection=docs"), "setup.mdx": () => import("../content/docs/setup.mdx?collection=docs"), "sponsors.mdx": () => import("../content/docs/sponsors.mdx?collection=docs"), "troubleshooting.mdx": () => import("../content/docs/troubleshooting.mdx?collection=docs"), "usage.mdx": () => import("../content/docs/usage.mdx?collection=docs"), "migrate/biome.mdx": () => import("../content/docs/migrate/biome.mdx?collection=docs"), "migrate/eslint.mdx": () => import("../content/docs/migrate/eslint.mdx?collection=docs"), "migrate/oxlint.mdx": () => import("../content/docs/migrate/oxlint.mdx?collection=docs"), "migrate/prettier.mdx": () => import("../content/docs/migrate/prettier.mdx?collection=docs"), "migrate/stylelint.mdx": () => import("../content/docs/migrate/stylelint.mdx?collection=docs"), "provider/biome.mdx": () => import("../content/docs/provider/biome.mdx?collection=docs"), "provider/eslint.mdx": () => import("../content/docs/provider/eslint.mdx?collection=docs"), "provider/oxlint.mdx": () => import("../content/docs/provider/oxlint.mdx?collection=docs"), "upgrade/v5.mdx": () => import("../content/docs/upgrade/v5.mdx?collection=docs"), "upgrade/v6.mdx": () => import("../content/docs/upgrade/v6.mdx?collection=docs"), "upgrade/v7.mdx": () => import("../content/docs/upgrade/v7.mdx?collection=docs"), }),
};
export default browserCollections;